fix: wait for Target.fetchFromTarget command
pyppeteer/pyppeteer pull request #130
Opened 2020-06-08 13:17 UTC by MorbidAngel

This changes solves the problem with:

```
asyncio default_exception_handler :1604 Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error (Target.detachFromTarget): No session with given id')>
```

error.

2020-06-08 16:07 UTC, Mattwmaster58 commented
Hi @MorbidAngel, thanks for the PR! Unfortunately, it seems this has already been implemented in #16.

2020-06-09 06:37 UTC, MorbidAngel commented
@Mattwmaster58 Hi, sorry I've missed that. Is it going to be merged into dev branch soon ?. Or should I use the pup2.1.1. branch instead (is this branch `pup2.1.1` stable enough to be used in the production) ?

2020-06-09 07:12 UTC, MorbidAngel commented
> Hi @MorbidAngel, thanks for the PR! Unfortunately, it seems this has already been implemented in #16.

Sorry, but I don't see any related change in the `https://github.com/pyppeteer/pyppeteer/pull/16/files#diff-5c728b692de8dbba0a50ecc6e6df6398R124`.

2020-06-09 20:45 UTC, Mattwmaster58 commented
Sorry about the false alart, I have to admit it's a knee jerk reaction to seeing a PR that isn't merging to pup2.1.1 just because of all the work we've done. If you could set the destination to pup2.1.1 and make that appropriate changes that would be great.

2020-06-10 06:42 UTC, MorbidAngel commented
Not a problem,  I've changed the base branch for this PR to the `pup2.1.1`. But still, I repeat my question - is `pup2.1.1` stable enough to be used on the production ?

2020-06-10 21:28 UTC, Mattwmaster58 commented
No, I wouldn't use it in production yet, even though I would consider it fairly stable for simple tasks.

2020-06-13 22:45 UTC, Mattwmaster58 requested changes
Nothing wrong with your implementation, I just couldn't resist improving the logging here 😉

2020-06-13 22:45 UTC, Mattwmaster58 commented on pyppeteer/page.py
>                      logger.error(f'An exception occurred: {e}')
```suggestion
                except Exception as e:
                    logger.exception(f'An exception occurred while trying to detach from target')
```

2020-06-15 14:35 UTC, Mattwmaster58 approved these changes

2020-06-15 14:35 UTC, merged