#154 Update launcher options to avoid OS.Error
pyppeteer/pyppeteer pull request #181
Opened 2020-10-16 19:53 UTC by Jflick58

Implemented and tested fix idea in #154 

Sure we can pass dumpio=True in the launcher options, but the DEVNULL change solves this error with the default behavior as well. I'm changing dumpio=True by default just to be safe.

2020-10-26 16:56 UTC, Granitosaurus commented
Looks good to me!

2020-11-13 22:49 UTC, Mattwmaster58 commented
Admittedly it's been a while since I've worked with dumpio but I don't think dumpio=True is the default we want. This would flood the console with stdout/err from the chrome process which I  don't think should be the default. If you didn't observe this behavior, I wouldn't be surprised the dumpio option was broken. But I don't think it should be the default.

2020-11-13 22:49 UTC, Mattwmaster58 requested changes
Admittedly it's been a while since I've worked with dumpio but I don't think dumpio=True is the default we want. This would flood the console with stdout/err from the chrome process which I don't think should be the default. If you didn't observe this behavior, I wouldn't be surprised the dumpio option was broken. But I don't think it should be the default.

2020-11-18 00:42 UTC, Jflick58 commented
@Mattwmaster58  made the change. Let me know if anything else is needed.

2020-11-28 08:17 UTC, nichoi commented
Any updates regarding this?

2020-11-30 17:56 UTC, Jflick58 commented
@nichoi  I requested @Mattwmaster58 's review on this since I've made the change.

2020-12-05 22:28 UTC, Mattwmaster58 approved these changes

2020-12-05 22:29 UTC, merged

2020-12-29 21:48 UTC, Mattwmaster58 commented
@nichoi, @Jflick58 A RC has been released with this fix: 0.2.3.rc1