add ported tests from puppeteer for page.click
pyppeteer/pyppeteer pull request #78
Opened 2020-04-12 05:07 UTC by Granitosaurus

2020-04-12 17:11 UTC, Mattwmaster58 commented on tests/test_click.py
> +    assert await frame.evaluate("() => window.result") == 'Clicked'
Looks like this is basically duplicated below, so I don't see why we wouldn't be able to remove it.

2020-04-12 17:20 UTC, Mattwmaster58 commented on tests/test_click.py
> +    await p.setViewport(dict(width=500, height=500, deviceScaleFactor=5))
I'd prefer a dict literal here
```suggestion
    await p.setViewport({'width': 500, 'height': 500, 'deviceScaleFactor': 5})
```

2020-04-12 17:21 UTC, Mattwmaster58 requested changes
Looks good for the most part. I would replace `'\(\) => ([\w\.]+)'` with `$1` though as it's more readable and functionally the same. (eg `() => window.CLICKED` gets replaced with `window.CLICKED`). Another thing is that you don't need the leading / when referring to a server destination. (ie `server / '/page.html'` can become `server / 'page.html'`, which IMO is more readable)

2020-04-13 07:17 UTC, Granitosaurus commented
Ah I didn't know the arrow functions aren't necessary, good to see we can get rid a bit of this clutter! Updated with your proposed style changes.

2020-04-13 09:32 UTC, merged