add tests for jshandle
pyppeteer/pyppeteer pull request #79
Opened 2020-04-13 13:24 UTC by Granitosaurus

2020-04-13 13:25 UTC, Granitosaurus commented
I couldn't figure out how to translate puppeteers:
```
await page.evaluateHandle(
          opts => opts.elem.querySelector('p'),
          { elem: aHandle }
      )
```

Any ideas?

2020-04-13 17:03 UTC, Mattwmaster58 requested changes
Minor details

2020-04-13 17:03 UTC, Mattwmaster58 commented on tests/test_jshandle.py
> +    # this should be able to take local reference
Must have glazed over the type definitions here, eval does in fact allow a JSHandle as an argument:
> Union['JSHandle', str, int, float, bool, None, Dict[str, Any], List[Any]]

```suggestion
async def test_handle_with_arg(isolated_page, server):
    """test getting handle"""
    p = isolated_page
    navigatorHandle = await p.evaluateHandle("navigator")
```

And the tests passes ✅

2020-04-13 17:03 UTC, Mattwmaster58 commented on tests/test_jshandle.py
> +        handle,  # todo translate {elem: handle}
It's JS's object literal notation:
```suggestion
        {'opts': handle}
```

2020-04-13 17:03 UTC, Mattwmaster58 commented on tests/conftest.py
> +CHROME = not _firefox
I'd prefer we make this a fixture to avoid having to import from `conftest`, or defixturizing `firefox` to be consistent. We can wait on that for now, though

2020-04-13 17:03 UTC, Mattwmaster58 commented on tests/test_jshandle.py
> +    """test getting handle"""
This doc strings seems to be repeated a lot, I'm guessing copy/pasting fn definitions?
Here's the live template I use in PyCharm:

```py
@sync
async def test_$fnname$($args$):
    $END$
```

2020-04-13 17:03 UTC, Mattwmaster58 commented on tests/test_jshandle.py
> +        handle,  # todo translate {elem: handle}
Unfortunately this test will hang and get terminated by `pytest-timeout`

2020-04-13 17:03 UTC, Mattwmaster58 commented on tests/test_jshandle.py
> +        assert e.match('Object reference chain is too long')
Wasn't aware of pytest's `match` method here, good to know

2020-04-13 17:03 UTC, Mattwmaster58 commented on tests/test_jshandle.py
> +    # )
Again, it actually does, and this test passes ✅

2020-04-14 01:42 UTC, Granitosaurus commented on tests/test_jshandle.py
> +    """test getting handle"""
Yeah I got live templates up at running myself. I think I'm just copying mindless comments from puppeteer upstream :grimacing: 

Here's my template:
```
@sync
async def test_$END$(isolated_page, server):
    p = isolated_page
```

2020-04-14 01:45 UTC, Granitosaurus commented on tests/test_jshandle.py
> +        handle,  # todo translate {elem: handle}
yeah that does hang the whole test suit, that's why I left it as a comment. Do you know what causes the hang? I think some some signals are malformed.

2020-04-14 15:42 UTC, Mattwmaster58 commented on tests/test_jshandle.py
> +        handle,  # todo translate {elem: handle}
Not sure why it hangs. I'm guessing we're getting a bit of a different response from the browser and not handling it correctly, leading to a send future that's never resolved. I've mitigated the effects of this by reducing the test timeout from 120s to just 10s. Our longest test in the suite (so far) takes around 5s on my dual core laptop from years ago, so I figured 10s just to be safe.

2020-04-19 13:16 UTC, merged