Add tests for frames
pyppeteer/pyppeteer pull request #81
Opened 2020-04-13 16:04 UTC by Granitosaurus

2020-04-13 17:22 UTC, Mattwmaster58 requested changes

2020-04-13 17:22 UTC, Mattwmaster58 commented on tests/test_frame.py
> +    # should throw for detached frames
In general I'd prefer more descriptive test fn names by default (and I think most of the tests in this file are appropriately named), but this name will provide almost no information when it fails.
```suggestion
async def test_evaluate_raises_on_detaches_frames(isolated_page, server):
    p = isolated_page
```

2020-04-13 17:22 UTC, Mattwmaster58 commented on tests/test_frame.py
> +async def test_attaching(isolated_page, server):
Same issue mentioned above

2020-04-13 17:22 UTC, Mattwmaster58 commented on tests/test_frame.py
> +    # TODO here detachedframes has more than 4 because it's filled with dupes
I'm assuming it doesn't anymore cause this test passes 😉

2020-04-13 17:22 UTC, Mattwmaster58 commented on tests/test_frame.py
> +    # should report frame from-inside shadow DOM
Function naming, mentioned earlier

2020-04-13 17:22 UTC, Mattwmaster58 commented on tests/test_frame.py
> +    assert frame1.isDetached is True
Nitpick, but more idiomatically expressed this could be `assert frame1.isDetached`

2020-04-13 20:52 UTC, Mattwmaster58 commented on tests/test_frame.py
> +    assert e.match('Execution Context is not available in detached frame')
IMO the inline exception message matching is a little better:
```suggestion
    with pytest.raises(BrowserError, match='Execution Context is not available in detached frame') as e:
        await frame1.evaluate('7 * 8')
```

2020-04-19 13:49 UTC, Granitosaurus commented
@Mattwmaster58 I resolve the comments and some tests were failing because of the fact that python sets are unordered while javascript's are. 

I think it would solve us a lot of headache to migrate sets to orderedsets as we can't really know when the importance of ordering could pop up.  
I've added OrderedSet dependancy in latest commit.

2020-04-19 15:06 UTC, Mattwmaster58 commented on pyppeteer/frame/__init__.py
> +        self._childFrames: OrderedSet[Frame] = OrderedSet()
There was an issue on the orderedset project asking about type hinting, and it implied this currently isn't possible. I think it's fine to keep it in for now though, there's hundreds of mypy errots and we can easily change this one in a batch of mypy fixes.

2020-04-19 17:37 UTC, Mattwmaster58 approved these changes

2020-05-16 02:32 UTC, merged

2020-06-16 14:17 UTC, adrianvanlan commented
Hello, first of all excellent work!
I wanted to know if you are thinking about "setContent".
Reference: https://github.com/puppeteer/puppeteer/blob/main/src/FrameManager.ts#L477-L485

2020-06-16 20:00 UTC, Mattwmaster58 commented
> I wanted to know if you are thinking about "setContent".

That's already implemented in the branch this PR merged too.